//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCode.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashCode.Net.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code {0} not found in bill table.
        /// </summary>
        internal static string _Listener_Elapsed_Code0NotFoundInBillTable {
            get {
                return ResourceManager.GetString("_Listener_Elapsed_Code0NotFoundInBillTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error accepting bill.
        /// </summary>
        internal static string AcceptBill_ErrorAcceptingBill {
            get {
                return ResourceManager.GetString("AcceptBill_ErrorAcceptingBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bill validator error. Alignment bills mechanism error..
        /// </summary>
        internal static string CashCodeErroList_BillValidatorErrorAlignmentBillsMechanismError {
            get {
                return ResourceManager.GetString("CashCodeErroList_BillValidatorErrorAlignmentBillsMechanismError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bill validator error. Inductance channel error..
        /// </summary>
        internal static string CashCodeErroList_BillValidatorErrorInductanceChannelError {
            get {
                return ResourceManager.GetString("CashCodeErroList_BillValidatorErrorInductanceChannelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bill validator error. Optical sensors error..
        /// </summary>
        internal static string CashCodeErroList_BillValidatorErrorOpticalSensorsError {
            get {
                return ResourceManager.GetString("CashCodeErroList_BillValidatorErrorOpticalSensorsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bill validator error. Stacking error.
        /// </summary>
        internal static string CashCodeErroList_BillValidatorErrorSendBillsToStackerError {
            get {
                return ResourceManager.GetString("CashCodeErroList_BillValidatorErrorSendBillsToStackerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bill validator error. Stacker error..
        /// </summary>
        internal static string CashCodeErroList_BillValidatorErrorStackerError {
            get {
                return ResourceManager.GetString("CashCodeErroList_BillValidatorErrorStackerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bill validator error. Stacker mechanism error..
        /// </summary>
        internal static string CashCodeErroList_BillValidatorErrorStackerMechanismError {
            get {
                return ResourceManager.GetString("CashCodeErroList_BillValidatorErrorStackerMechanismError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bill validator error. Stacker occupancy channel error..
        /// </summary>
        internal static string CashCodeErroList_BillValidatorErrorStackerOccupancyCheckChannelError {
            get {
                return ResourceManager.GetString("CashCodeErroList_BillValidatorErrorStackerOccupancyCheckChannelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bill validator error. Stacker transmission speed error..
        /// </summary>
        internal static string CashCodeErroList_BillValidatorErrorStackerTransmissionSpeedError {
            get {
                return ResourceManager.GetString("CashCodeErroList_BillValidatorErrorStackerTransmissionSpeedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на COM-port is closed..
        /// </summary>
        internal static string CashCodeErroList_ComPortNotOpen {
            get {
                return ResourceManager.GetString("CashCodeErroList_ComPortNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error checking of status of the bill validator. Fake bill..
        /// </summary>
        internal static string CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorFakeBill {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorFakeBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error checking of status of the bill validator. Stacker is full..
        /// </summary>
        internal static string CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorStackerIsFull {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorStackerIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error checking bill validator status. Stacker is down..
        /// </summary>
        internal static string CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorStackerSDown {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorStackerSDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error checking of status of the bill validator. The previous bill has not yet hit the stack and is in the recognition mechanism..
        /// </summary>
        internal static string CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorThePreviousBillHasNotYetHitTheStackAndIsInTheRecognitionMechanism {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorThePreviousBillHasNotYetH" +
                        "itTheStackAndIsInTheRecognitionMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error checking of status of the bill validator. There&apos;s a bill stuck in the stacker..
        /// </summary>
        internal static string CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorThereSABillStuckInTheStacker {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorThereSABillStuckInTheStac" +
                        "ker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error checking of status of the bill validator. There&apos;s a bill stuck in the validator..
        /// </summary>
        internal static string CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorThereSABillStuckInTheValidator {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorCheckingOfStatusOfTheBillValidatorThereSABillStuckInTheVali" +
                        "dator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error sending command to enable the bill validator.
        /// </summary>
        internal static string CashCodeErroList_ErrorOffspringOfTheCommandToEnableTheBillValidator {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorOffspringOfTheCommandToEnableTheBillValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error sending command to enable the bill validator. No ACK message was received from the bill validator..
        /// </summary>
        internal static string CashCodeErroList_ErrorOffspringOfTheCommandToEnableTheBillValidatorNoACKCommandWasReceivedFromTheBillValidator {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorOffspringOfTheCommandToEnableTheBillValidatorNoACKCommandWa" +
                        "sReceivedFromTheBillValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error sending command to enable the bill validator. No INITIALIZE message was received from the bill validator..
        /// </summary>
        internal static string CashCodeErroList_ErrorOffspringOfTheCommandToEnableTheBillValidatorNoINITIALIZECommandWasReceivedFromTheBillValidator {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorOffspringOfTheCommandToEnableTheBillValidatorNoINITIALIZECo" +
                        "mmandWasReceivedFromTheBillValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error sending command to enable the bill validator. No POWER UP message was received from the bill validator..
        /// </summary>
        internal static string CashCodeErroList_ErrorOffspringOfTheCommandToEnableTheBillValidatorNoPOWERUPCommandWasReceivedFromTheBillValidator {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorOffspringOfTheCommandToEnableTheBillValidatorNoPOWERUPComma" +
                        "ndWasReceivedFromTheBillValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error opening COM-port..
        /// </summary>
        internal static string CashCodeErroList_ErrorOpeningComPort {
            get {
                return ResourceManager.GetString("CashCodeErroList_ErrorOpeningComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Capacity.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToCapacity {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Conveying.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToConveying {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToConveying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Identification!.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToIdentification1 {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToIdentification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Inhibit.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToInhibit {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToInhibit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Insertion.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToInsertion {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToInsertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Length.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToLength {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Magnetic.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToMagnetic {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToMagnetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Multiplying.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToMultiplying {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToMultiplying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Operation.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToOperation {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Optic.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToOptic {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToOptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Remained bill in head.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToRemainedBillInHead {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToRemainedBillInHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting due to Verification.
        /// </summary>
        internal static string CashCodeErroList_RejectingDueToVerification {
            get {
                return ResourceManager.GetString("CashCodeErroList_RejectingDueToVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown error..
        /// </summary>
        internal static string CashCodeErroList_UnknownError {
            get {
                return ResourceManager.GetString("CashCodeErroList_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error enabling bill reception. You should call the StartListening method..
        /// </summary>
        internal static string EnableBillValidator_ErrorInTheMethodOfEnablingTheReceptionOfBanknotesYouMustCallTheStartListeningMethod {
            get {
                return ResourceManager.GetString("EnableBillValidator_ErrorInTheMethodOfEnablingTheReceptionOfBanknotesYouMustCallT" +
                        "heStartListeningMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error return bill.
        /// </summary>
        internal static string RejectBill_ErrorReturnBill {
            get {
                return ResourceManager.GetString("RejectBill_ErrorReturnBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received message checksum mismatch. The device may not be connected to the COM port. Check your connection settings..
        /// </summary>
        internal static string SendCommand_TheMismatchOfTheChecksumOfTheReceivedMessageTheDeviceMayNotBeConnectedToTheCOMPortCheckYourConnectionSettings {
            get {
                return ResourceManager.GetString("SendCommand_TheMismatchOfTheChecksumOfTheReceivedMessageTheDeviceMayNotBeConnecte" +
                        "dToTheCOMPortCheckYourConnectionSettings", resourceCulture);
            }
        }
    }
}
